import "./_globalCss/globals.css";
import "./_globalCss/all.min.css";
import { Inter } from "next/font/google";
import { InfoContextProvider } from "./useInfo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <InfoContextProvider>{children}</InfoContextProvider>
      </body>
    </html>
  );
}
